name: MLOps/task-6

services:
  task6-server:
    build:
      context: ..
      dockerfile: ./task-6/Dockerfile-server
    volumes:
      - ./logs:/app/task-6/logs
      - ./models:/app/task-6/models:ro
      - ./meta.json:/app/task-6/meta.json:ro

  task6-client:
    build:
      context: ..
      dockerfile: ./task-6/Dockerfile-client
    ports:
      - "8501:8501"
    environment:
      API_URL: "task6-server:8000"
    depends_on:
      - task6-server